FROM quay.io/helmpack/chart-testing:v2.2.0

LABEL "com.github.actions.name"="Chart Testing"
LABEL "com.github.actions.description"="Write arguments to the standard output"
LABEL "com.github.actions.icon"="mic"
LABEL "com.github.actions.color"="blue"

LABEL "repository"="http://github.com/flydiverny/actions"
LABEL "homepage"="http://github.com/flydiverny/actions"
LABEL "maintainer"="Markus Maga <markus@maga.se>"

ENTRYPOINT ["ct"]
CMD ["help"]
