FROM quay.io/helmpack/chart-testing:latest

LABEL "com.github.actions.name"="Helm Chart Testing"
LABEL "com.github.actions.description"="Runs chart-testing "
LABEL "com.github.actions.icon"="anchor"
LABEL "com.github.actions.color"="blue"

LABEL "repository"="http://github.com/flydiverny/actions"
LABEL "homepage"="http://github.com/flydiverny/actions"
LABEL "maintainer"="Markus Maga <markus@maga.se>"

ENTRYPOINT ["ct"]
CMD ["help"]
