FROM flydiverny/chart-releaser:latest

LABEL "com.github.actions.name"="Chart Releaser"
LABEL "com.github.actions.description"="Write arguments to the standard output"
LABEL "com.github.actions.icon"="mic"
LABEL "com.github.actions.color"="blue"

LABEL "repository"="http://github.com/flydiverny/actions"
LABEL "homepage"="http://github.com/flydiverny/actions"
LABEL "maintainer"="Markus Maga <markus@maga.se>"

ENTRYPOINT ["/bin/chart-releaser"]
CMD ["help"]
